import { getPostData } from "@/lib/blog";

export default async function BlogPost(props: any) {
    const params = await props.params;

    const post = await getPostData(params.slug);
    
    return (
        <article>
            <h1>{post.frontmatter.title}</h1>
            <div>{post.frontmatter.date}</div>
            {/* This inserts the raw HTML generated by remark */}
            <div dangerouslySetInnerHTML={{ __html: post.contentHTML }} />
        </article>
    )
    
}