import { getPostData, getSortedBlogData } from "@/lib/blog";

// Generate static params so all blog posts are pre-rendered at built time
export async function generateStaticParams() {
    const posts = getSortedBlogData();
    return posts.map((post) => ({ slug: post.id }));
}

export default async function BlogPost(props: any) {
    const params = await props.params;

    const post = await getPostData(params.slug);
    
    return (
        <article>
            <h1>{post.frontmatter.title}</h1>
            <div>{post.frontmatter.date}</div>
            {/* This inserts the raw HTML generated by remark */}
            <div dangerouslySetInnerHTML={{ __html: post.contentHTML }} />
        </article>
    )
    
}