import type { Metadata } from "next";
import { Inter, Source_Code_Pro, Space_Grotesk } from "next/font/google";
import "./globals.css";
import NavBar from "./_components/Navbar";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-space-grotesk',
  display: 'swap'
})

const sourceCodePro = Source_Code_Pro({
  subsets: ['latin'],
  variable: "--font-source-code-pro",
  display: 'swap'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${spaceGrotesk.variable} ${sourceCodePro.variable}`}>
      <body
        className={`${inter.className} antialiased max-w-6xl mx-auto py-10 px-4`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
